---
title: "Research"
output: html_document
---

I started out as an undergraduate student of Psychology at Trier University, Germany, where I became especially fascinated with Social Psychology. Eventually, I joined the [Social Psyc lab](https://www.uni-trier.de/index.php?id=5803&L=2) as a student assistant where I came to love the meticulous planning that goes along with experimental Psychology. My final thesis addressed how long-term memory influences the integration of an object’s features into a wholesome perceptual experience. My advisors were [Eva Walter](https://www.uni-trier.de/index.php?id=21130&L=2) and [Katarina Blask](https://www.uni-trier.de/index.php?id=33444&L=2).

I spent some time at the [Max-Planck-Institute for Human Cognitive and Brain Sciences](http://www.cbs.mpg.de/de) in Leipzig, Germany, where I worked with the research group directed by [Tom Fritz](http://www.cbs.mpg.de/departments/neurology/music-evoked-brain-plasticity) The small research project I conducted here was moving along the intersection of Neuroscience and the study of music. As an enthusiast of both, this was an amazing opportunity and I came to appreciate the truly close relationship between art and science.

After this intermezzo, I enrolled as a Masters student at the [Otto-von-Guericke University in Magdeburg, Germany](http://www.ipsy.ovgu.de/ipsy/en/). Here, my focus has shifted from general Psychology to Neuroscience. I am especially fascinated by the developments in fMRI methods, such as functional connectivity and the study of representation by means of multi voxel pattern and representational similarity analysis.

In Magdeburg, I also had the opportunity to work as a research assistant in the [Department of Experimental Psychology](http://www.ipsy.ovgu.de/en/exppsy.html). I was involved in behavioral and fMRI studies of vision and learning which culminated in a publication by [Fariba Sharifian](https://sites.google.com/site/fsharifian/), wich I contributed to.

I also spent a summer as a research intern in [James Haxby's lab](http://haxbylab.dartmouth.edu/) at [Dartmouth College](http://pbs.dartmouth.edu/) getting deeper into fMRI analysis. I explored how the neural representation of familiar and unfamiliar faces changes over time as well as the interconnectedness of the modules in the face processing system. This work will provide the grounding of my upcoming Masters thesis. In Dartmouth, I was very lucky to work closely with [Yaroslav Halchenko](http://haxbylab.dartmouth.edu/ppl/yarik.html). He was an amazing supervisor and a good friend.

MORE ON OPEN SCIENCE.

MY CURRENT JOB IN MAGDEBURG.